export const ARTICLE_LOADING = 'ARTICLE_LOADING';
export const ARTICLE_FAILED = 'ARTICLE_FAILED';
export const LOAD_ARTICLE = 'LOAD_ARTICLE';
export const ADD_ARTICLE = 'ADD_ARTICLE';

export const ARTICLES_LOADING = 'ARTICLES_LOADING';
export const ARTICLES_FAILED = 'ARTICLES_FAILED';
export const LOAD_ARTICLES = 'LOAD_ARTICLES';
export const ADD_ARTICLES = 'ADD_ARTICLES';